In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

# Load the Dataset

In [2]:
data = pd.read_csv('dataset/Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

# Encoding

In [4]:
encoder = OneHotEncoder(drop=None,sparse_output = False)
encoded_df=encoder.fit_transform(data[['Gender', 'Geography']])

In [5]:
encoded_df = pd.DataFrame(encoded_df,columns=encoder.get_feature_names_out(['Gender','Geography']))
encoded_df

,Gender_Female,Gender_Male,Geography_France,Geography_Germany,Geography_Spain
0,1.0,0.0,1.0,0.0,0.0
1,1.0,0.0,0.0,0.0,1.0
2,1.0,0.0,1.0,0.0,0.0
3,1.0,0.0,1.0,0.0,0.0
4,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...
9995,0.0,1.0,1.0,0.0,0.0
9996,0.0,1.0,1.0,0.0,0.0
9997,1.0,0.0,1.0,0.0,0.0
9998,0.0,1.0,0.0,1.0,0.0
9999,1.0,0.0,1.0,0.0,0.0

In [6]:
data = pd.concat([data.drop(['Geography','Gender'],axis=1),encoded_df],axis=1)

In [7]:
data.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_Female,Gender_Male,Geography_France,Geography_Germany,Geography_Spain
0,619,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,1.0,0.0,0.0
1,608,41,1,83807.86,1,0,1,112542.58,0,1.0,0.0,0.0,0.0,1.0
2,502,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,1.0,0.0,0.0
3,699,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,1.0,0.0,0.0
4,850,43,2,125510.82,1,1,1,79084.10,0,1.0,0.0,0.0,0.0,1.0

In [8]:
## Save this encoding in pickle file
with open('artifacts/encoder.pkl','wb') as file:
    pickle.dump(encoder,file)

# Independent and Dependent Features

In [9]:
X = data.drop('Exited',axis=1)
y=data['Exited']

In [10]:
X.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Gender_Female,Gender_Male,Geography_France,Geography_Germany,Geography_Spain
0,619,42,2,0.00,1,1,1,101348.88,1.0,0.0,1.0,0.0,0.0
1,608,41,1,83807.86,1,0,1,112542.58,1.0,0.0,0.0,0.0,1.0
2,502,42,8,159660.80,3,1,0,113931.57,1.0,0.0,1.0,0.0,0.0
3,699,39,1,0.00,2,0,0,93826.63,1.0,0.0,1.0,0.0,0.0
4,850,43,2,125510.82,1,1,1,79084.10,1.0,0.0,0.0,0.0,1.0

In [11]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

# Train Test Split

In [12]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

# Scaling

In [13]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
X_train

array([[ 0.21835119,  1.91661905, -1.73168869, ...,  1.00053348,
        -0.57776083, -0.57735027],
       [ 2.05728037,  0.20210899,  1.04174968, ..., -0.99946681,
         1.73082   , -0.57735027],
       [ 0.75860157, -0.75039661,  0.34839008, ...,  1.00053348,
        -0.57776083, -0.57735027],
       ...,
       [ 0.86249588, -0.08364269, -1.3850089 , ...,  1.00053348,
        -0.57776083, -0.57735027],
       [ 0.15601461,  0.3926101 ,  1.04174968, ...,  1.00053348,
        -0.57776083, -0.57735027],
       [ 0.46769752,  1.15461458, -1.3850089 , ..., -0.99946681,
         1.73082   , -0.57735027]], shape=(7500, 13))

In [15]:
## Save this scaler in pickle
with open('artifacts/scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

# ANN

In [16]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [17]:
## Build ANN Model
model = Sequential([
            Input(shape=(X_train.shape[1],)),
            Dense(64,activation='relu'), ##HL 1
            Dense(32,activation='relu'),  ##HL 2
            Dense(1,activation='sigmoid') ##Output
])

In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,009 (11.75 KB)

 Trainable params: 3,009 (11.75 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
opt=tf.keras.optimizers.Adam(learning_rate=0.01)
loss=tf.keras.losses.BinaryCrossentropy()

In [20]:
## Compile model
model.compile(optimizer=opt,loss=loss,metrics=["accuracy"])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [21]:
## Set up the TensorBoard
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [22]:
## Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

In [23]:
## Training Model
history = model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 9s 13ms/step - accuracy: 0.8304 - loss: 0.3982 - val_accuracy: 0.8560 - val_loss: 0.3671
Epoch 2/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8513 - loss: 0.3610 - val_accuracy: 0.8552 - val_loss: 0.3513
Epoch 3/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.8517 - loss: 0.3537 - val_accuracy: 0.8612 - val_loss: 0.3463
Epoch 4/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8568 - loss: 0.3463 - val_accuracy: 0.8612 - val_loss: 0.3505
Epoch 5/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8609 - loss: 0.3400 - val_accuracy: 0.8576 - val_loss: 0.3477
Epoch 6/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8595 - loss: 0.3403 - val_accuracy: 0.8592 - val_loss: 0.3450
Epoch 7/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8621 - loss: 0.3380 - val_accuracy: 0.8616 - val_loss: 0.3476
Epoch 8/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8613 - loss: 0.3360 - val_accuracy: 0.8600 - val_loss: 0.3621
Epoch 9/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8659 - loss: 0.3327 - val_accuracy: 0.8584 - val_loss: 0.3498
Epoch 10/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8667 - loss: 0.3310 - val_accuracy: 0.8600 - val_loss: 0.3417
Epoch 11/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8624 - loss: 0.3313 - val_accuracy: 0.8592 - val_loss: 0.3502
Epoch 12/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8631 - loss: 0.3295 - val_accuracy: 0.8600 - val_loss: 0.3485
Epoch 13/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8661 - loss: 0.3263 - val_accuracy: 0.8520 - val_loss: 0.3840
Epoch 14/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8625 - loss: 0.3272 - val_accuracy: 0.8604 - val_loss: 0.3479
Epoch 15/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8644 - loss: 0.3226 - val_accuracy: 0.8592 - val_loss: 0.3587
Epoch 16/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8695 - loss: 0.3217 - val_accuracy: 0.8568 - val_loss: 0.3483
Epoch 17/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8680 - loss: 0.3204 - val_accuracy: 0.8560 - val_loss: 0.3585
Epoch 18/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8691 - loss: 0.3183 - val_accuracy: 0.8612 - val_loss: 0.3468
Epoch 19/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8687 - loss: 0.3166 - val_accuracy: 0.8628 - val_loss: 0.3533
Epoch 20/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8720 - loss: 0.3136 - val_accuracy: 0.8652 - val_loss: 0.3545

In [24]:
model.save('artifacts/model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.