In [57]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

# Loading All Trained Models

In [58]:
model = load_model('artifacts/model.h5')

with open('artifacts/encoder.pkl','rb') as file:
    encoder = pickle.load(file)

with open('artifacts/scaler.pkl','rb') as file:
    scaler = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [59]:
## Example data
input_data = {
    'CreditScore':600,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

In [60]:
input_data_df = pd.DataFrame([input_data])
input_data_df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [61]:
encoded = encoder.transform([[input_data['Gender'],input_data['Geography']]])

encoded_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out(['Gender','Geography']))

c:\Projects\Bank-Retention-Analysis\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [62]:
encoded_df.head()

,Gender_Female,Gender_Male,Geography_France,Geography_Germany,Geography_Spain
0,0.0,1.0,1.0,0.0,0.0

In [63]:
input_data_df = pd.concat([input_data_df.drop(['Gender','Geography'],axis=1),encoded_df],axis=1)

In [64]:
input_data_df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Gender_Female,Gender_Male,Geography_France,Geography_Germany,Geography_Spain
0,600,40,3,60000,2,1,1,50000,0.0,1.0,1.0,0.0,0.0

In [65]:
input_scaled=scaler.transform(input_data_df)

In [66]:
input_scaled

array([[-0.54007722,  0.10685843, -0.69164931, -0.26034447,  0.81311138,
         0.64946204,  0.96978946, -0.88017893, -0.91186722,  0.91186722,
         1.00053348, -0.57776083, -0.57735027]])

In [67]:
##Predict Churn
prediction = model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step

array([[0.04976571]], dtype=float32)

In [68]:
prediction_proba = prediction[0][0]

In [69]:
prediction_proba

np.float32(0.049765706)

In [70]:
if prediction_proba>0.5:
    print("Th customer is likely to churn")

print('Customer is not likely to churn')

Customer is not likely to churn